POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Coach School - Begin",
  "details": "A Coach School, is a school for peoples that want to improve your personal performance ",
  "maximumAttendees": 2
}

###

POST  http://localhost:3333/events/d6d6c065-5f35-4495-8100-21ade307652a/attendee
Content-Type: application/json

{
  "name": "Micaelly Fontanesi",
  "email": "micaelly@gmail.com"
}

###

GET http://localhost:3333/event/172fb824-6fc6-450a-83ae-86d3eebd0fc0
Content-Type: application/json