POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Batalha da Aldeia 8 Aniversario",
  "details": "É so os índios mais pesados da tribu que incendeia!",
  "maximumAttendees": 250
}