POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Teste",
  "details": "teste",
  "maximumAttendees": 1
}

###

POST  http://localhost:3333/events/b9b7a0e4-8b39-4769-b55e-e72fc0ac1474/attendee
Content-Type: application/json

{
  "name": "Esdras Castro",
  "email": "esdras.cff@gmail.com"
}